### Full Code re-indent! switched from ksh indent (2 spaces) to bash indent (4 spaces)

diff --git a/tewiba b/tewiba
--- a/tewiba
+++ b/tewiba
@@ -110,12 +110,12 @@ V(){ :;};T(){ :;};v=false;E(){ echo "$@";};En(){ E -n "$@";};VV(){ :;};nl=$'\n'
 err(){ E "***ERROR: $*" >&2; exit 1;};warn(){ E "###Warning: $*" >&2;}
 while getopts ":${OPTIONS}hv?" _o; do case "$_o" in
 #----single letter options start-----------------------------------------
-  e) statusfile="$OPTARG";;
-  l) TLEVELS="$OPTARG";;
-  x) debug=true; rm -f $debuglog;;
-  s) ts_standalone=true;;
-  f) must_tend=false;;
-  V) echo "$TEWIBA"; exit 0;;
+    e) statusfile="$OPTARG";;
+    l) TLEVELS="$OPTARG";;
+    x) debug=true; rm -f $debuglog;;
+    s) ts_standalone=true;;
+    f) must_tend=false;;
+    V) echo "$TEWIBA"; exit 0;;
 #----single letter options end-------------------------------------------
 v)T(){ local i;{ En "==";for i in "$@";do [[ $i =~ [^_[:alnum:]] ]]&&En " $i"||
 En " $i=${!i}";done;E;}>&2;};V(){ E "== $*" >&2;};v=true;;h) E "$USAGE"
@@ -149,13 +149,13 @@ FERR () {
 }
 TEND () { ts_exit $TFAILS; }
 TINIT () { # _TINITS is a per-dir file containing the loaded IDs
-  local id="${1//[^-_.a-zA-Z0-9/}"; [ -n "$id" ] || return; 
-  fgrep -qxs $id $_TINITS && return; echo $id >>$_TINITS
-  [ -x __INIT__$id ] && source __INIT__$id
+    local id="${1//[^-_.a-zA-Z0-9/}"; [ -n "$id" ] || return; 
+    fgrep -qxs $id $_TINITS && return; echo $id >>$_TINITS
+    [ -x __INIT__$id ] && source __INIT__$id
 }
 TCLEANUP () { # with guards to avoid disaster if a test undefined the vars
-  [ -n "$_twtmp" ] && rm -rf $_twtmp $_twtmp.*
-  [ -n "$tmp" ] && rm -rf $tmp $tmp.*
+    [ -n "$_twtmp" ] && rm -rf $_twtmp $_twtmp.*
+    [ -n "$tmp" ] && rm -rf $tmp $tmp.*
 }
 trap TCLEANUP 0
 # low-level exit, runs TCLEANUP for safety if our trap 0 was overriden
@@ -187,28 +187,30 @@ export -f TLEVEL TEST TERR FERR TEND TINIT ts_exit TCLEANUP DOTEST
 
 # cautious cd
 err_cd () {
-  cd "$1" 2>/dev/null || \
-  err "tewiba failed to enter test dir: "$(readlink -m "$1")
+    cd "$1" 2>/dev/null || \
+	err "tewiba failed to enter test dir: "$(readlink -m "$1")
 }
 
 # executes all the tests that are direct sons of a dir
 ts_dir () {
-  local i oldpwd="$PWD" id
-  err_cd "$1"
-  export _TINITS=${_TINITS}x
-  for i in *; do
-    if [ -d "$i" ]; then
-      [[ $i =~ [.]subtests$ ]] && ts_dir "$i"
-    else
-      [[ $i =~ (^[#._]|~$) ]] || [ ! -x "$i" ] || [ "$i" = tewiba ] && 
-      continue
-      ts_test "$i"
+    local i oldpwd="$PWD" id
+    err_cd "$1"
+    export _TINITS=${_TINITS}x
+    for i in *; do
+	if [ -d "$i" ]; then
+	    [[ $i =~ [.]subtests$ ]] && ts_dir "$i"
+	else
+	    [[ $i =~ (^[\#._]|~$) ]] || [ ! -x "$i" ] || [ "$i" = tewiba ] && \
+		continue
+	    ts_test "$i"
+	fi
+    done
+    if [ -s $_TINITS ]; then 
+	for id in $(cat $_TINITS); do
+	    [ -x __END__$id ] && source __END__$id
+	done
     fi
-  done
-  if [ -s $_TINITS ]; then 
-    for id in $(cat $_TINITS); do [ -x __END__$id ] && source __END__$id; done
-  fi
-  cd "$oldpwd"
+    cd "$oldpwd"
 }
 
 # go execute a test in its directory env
@@ -221,69 +223,70 @@ ts_test_path () {
 
 # on entering a dir, execute __INIT__
 ts_init () {
-  $ts_standalone && return
-  local tdir=$(/bin/pwd)
-  if [ "$tdir" != "$_TDIR" ]; then
-    ts_end
-    [ -x __INIT__ ] && source __INIT__
-    _TDIR="$tdir"
-  fi
+    $ts_standalone && return
+    local tdir=$(/bin/pwd)
+    if [ "$tdir" != "$_TDIR" ]; then
+	ts_end
+	[ -x __INIT__ ] && source __INIT__
+	_TDIR="$tdir"
+    fi
 }
 # on leaving, execute __END__
 ts_end () {
-  [ -n "$_TDIR" ] && [ -x "$_TDIR"/__END__ ] && { 
-    local TODIR="$PWD"; cd "$_TDIR"; source __END__; cd "$TODIR"
-  }
+    if [ -n "$_TDIR" ] && [ -x "$_TDIR"/__END__ ]; then
+	local TODIR="$PWD"; cd "$_TDIR"; source __END__; cd "$TODIR"
+    fi
 }
 
 # will this test be run for the current level?
 # $1=test file, returns 0 if OK
 # we pre-detect it before running TLEVEL in file, avoiding extra "test ok" mess
 ts_level () {
-  local tlevel=$(grep -oP '^[[:space:]]*TLEVEL +\K.*' "$1")
-  [ -z "$tlevel" ] && return 0 # no TLEVEL line => OK
-  [ -z "$TLEVELS" ] || [[ $tlevel =~ [$TLEVELS] ]] || return 1
-  return 0
+    local tlevel=$(grep -oP '^[[:space:]]*TLEVEL +\K.*' "$1")
+    [ -z "$tlevel" ] && return 0 # no TLEVEL line => OK
+    [ -z "$TLEVELS" ] || [[ $tlevel =~ [$TLEVELS] ]] || return 1
+    return 0
 }
 
 # execute a single test in the current directory
 ts_test () {
-  local t="$1" s="#################################"
-  ts_level "$t" || return
-  ! egrep -q '^([^#]*;|[[:space:]]*)TEND([;[:space:]]|$)' "$t" && $must_tend &&
-  ! grep -q '^ *#TNOEND' "$t" && [ -s "$t" ] && \
-      err "Test file \"$t\" does not have a TEND statement. Use -f to force."
-  ts_init
-  _TEST_CURRENT="${t##*/}" # default TEST name: the filename
-  TFAILS=0
-  if $debug; then
-    echo "$s$s$nl$s Test file: $t$nl$s$s" >>$debuglog
+    local t="$1" s="#################################"
+    ts_level "$t" || return
+    ! egrep -q '^([^#]*;|[[:space:]]*)TEND([;[:space:]]|$)' "$t" && \
+	$must_tend && \
+	! grep -q '^ *#TNOEND' "$t" && [ -s "$t" ] && \
+	err "Test file \"$t\" does not have a TEND statement. Use -f to force."
+    ts_init
+    _TEST_CURRENT="${t##*/}" # default TEST name: the filename
+    TFAILS=0
+    if $debug; then
+	echo "$s$s$nl$s Test file: $t$nl$s$s" >>$debuglog
     # RUN + Trace
-    bash -x "$t" >>$debuglog 2>&1; status=$?
-  else
-    $TV && echo -n "== Test file: $t:"
-    # RUN
-    ./"$t" >$_twtmp.out 2> >(tee -a $_twtmp.err >&1); status=$?
-    let '_ts_failures += status'
-    if [ $status = 0 ]; then
-      if test -s $_twtmp.err; then 
-	if $TV; then echo "OK, but printed on stderr:"
-	else echo "###Warning: test $t OK, but printed on stderr:"
-	fi
-	print_indent $_twtmp.err
-      else
-	$TV && echo " OK"
-      fi
+	bash -x "$t" >>$debuglog 2>&1; status=$?
     else
-      if $TV; then echo "***ERRORS:$status"
-      else 
-	  echo "***FAILED ($status ERRORS): $t"
+	$TV && echo -n "== Test file: $t:"
+    # RUN
+	./"$t" >$_twtmp.out 2> >(tee -a $_twtmp.err >&1); status=$?
+	let '_ts_failures += status'
+	if [ $status = 0 ]; then
+	    if test -s $_twtmp.err; then 
+		if $TV; then echo "OK, but printed on stderr:"
+		else echo "###Warning: test $t OK, but printed on stderr:"
+		fi
+		print_indent $_twtmp.err
+	    else
+		$TV && echo " OK"
+	    fi
+	else
+	    if $TV; then echo "***ERRORS:$status"
+	    else 
+		echo "***FAILED ($status ERRORS): $t"
 	  if test -s $_twtmp.err; then print_indent $_twtmp.err; fi
-      fi
+	    fi
+	fi
+	if $TV && test -s $_twtmp.out; then print_indent $_twtmp.out; fi
+	[ -n "$tmp" ] && rm -rf $tmp $tmp.*
     fi
-    if $TV && test -s $_twtmp.out; then print_indent $_twtmp.out; fi
-    [ -n "$tmp" ] && rm -rf $tmp $tmp.*
-  fi
 }
 
 # print test outputs indented by 3 spaces for lisibility
@@ -294,16 +297,16 @@ print_indent () { sed -e 's/^/   /' <"$1"; }
 # run all tests given in arguments, or in the current dir if none given
 if [ $# == 0 ]; then ts_dir .
 else
-  for t in "$@"; do
-    if [  -d "$t" ]; then ts_dir "$t"
-    elif [ -x "$t" ]; then 
-      if [[ $t =~ / ]]; then ts_test_path "$t"
-      else ts_test "$t"
-      fi
-    elif [ -e "$t" ]; then err "$t not found!"
-    else err "$t is not executable!"
-    fi
-  done
+    for t in "$@"; do
+	if [  -d "$t" ]; then ts_dir "$t"
+	elif [ -x "$t" ]; then 
+	    if [[ $t =~ / ]]; then ts_test_path "$t"
+	    else ts_test "$t"
+	    fi
+	elif [ -e "$t" ]; then err "$t not found!"
+	else err "$t is not executable!"
+	fi
+    done
 fi
 ts_end
 
