v 1.5.0-beta.11 ECHO supports colors via TEWIBA_COLORS

diff --git a/tewiba b/tewiba
--- a/tewiba
+++ b/tewiba
@@ -1,5 +1,5 @@
 #!/bin/bash
-export TEWIBA=1.5.0-beta.10
+export TEWIBA=1.5.0-beta.11
 USAGE='tewiba [options] [tests...]
 Tewiba: TEst WIth BAsh: a simple test suite, in the spirit of shell scripting
 Runs the test suite, on all tests in the current dir (default), 
@@ -21,7 +21,8 @@ or on specific tests or directories of tests given as arguments.
 
 How to write tests:
    * Tests are executable files (in any language), that exit with code 0 if OK,
-     and the number of failures if not
+     and the number of failures if not. Since tewiba adds them to determine
+     the final fails count, do not use negative status, e.g. no "exit -1"
    * Test file names can be meaningful, e.g: "Test for empty input"
    * When running on a whole dir, ignores files beginning with ., _, and #,
      ending with ~, empty, not executable, non-bash scripts (they must have 
@@ -37,9 +38,6 @@ Filenames beginning with a "." "#" "_" or ending with "~" are ignored
      they will be automatically cleaned afterwards by rm -rf $tmp $tmp.*
    * Test data can be put in subdirectories, as subdirectories are not tested
    * Convenience functions & variables that you can use in bash script tests:
-     TLEVEL chars  only runs if a level in chars is in the ones given by -l,
-                   or -l not specified. Each level is an alphanumeric char.
-     TLEVEL_ONLY chars    Same as above but does not run if -l not given 
      TEST message  prints sub-test (the file name is the test name) name if 
                    verbose, and as label in TERR messages.
      TERR message  declares an error, but continues the tests.
@@ -47,10 +45,6 @@ Filenames beginning with a "." "#" "_" or ending with "~" are ignored
      TEND          MANDATORY: terminates your test script.
                    (an alias for: exit $TFAILS)
                    This is the only function really mandatory in a test file.
-     TINIT id...   For each id (composed of letters, numbers, and _ - .)
-                   ensures that files __INIT__id and __END__id are sourced,
-                   if they exist, before and after all tests of the file,
-                   after and before __INIT__ and __END__ respectively.
      DOTEST options command parameters..,
                    runs the command with parameters, and compare it to the 
                    expected result(s) in options, and trigger TERR for each
@@ -70,8 +64,22 @@ Filenames beginning with a "." "#" "_" or ending with "~" are ignored
                    -S let-expr  expects let arithmetic expression to be true,
                                 with the variable "status" holding the status
      TECHO text    An echo that prints on stderr, only in verbose mode, but
-                   that yewiba do not confuse with code errors in subtests.
-     TECHOF text   Same, but prints also in non-verbose mode.
+                   that tewiba do not confuse with code errors in subtests.
+                   -n      do not terminate by a newline, as with echo -n
+                   -v      (default) only prints in verbose move (TV == true)
+                   -f      forces printing even in non-verbose mode
+                   -c key  if the output is on a terminal, colors the
+                           text as defined for key in $TEWIBA_COLORS
+                           key can be just the first letter(s) of the 
+                           predefined keys, or any key you added to
+                           $TEWIBA_COLORS
+     TINIT id...   For each id (composed of letters, numbers, and _ - .)
+                   ensures that files __INIT__id and __END__id are sourced,
+                   if they exist, before and after all tests of the file,
+                   after and before __INIT__ and __END__ respectively.
+     TLEVEL chars  only runs if a level in chars is in the ones given by -l,
+                   or -l not specified. Each level is an alphanumeric char.
+     TLEVEL_ONLY chars    Same as above but does not run if -l not given 
      TWEIBA_IGNORE regular expressions...
                    ignores the file names matching expressions (for [[ =~ ]])
                    should be used in a __INIT__ file to apply to the whole dir
@@ -79,6 +87,23 @@ Filenames beginning with a "." "#" "_" or ending with "~" are ignored
      $TV           is true in tewiba verbose mode, false otherwise.
      $tmp          temporary data prefix (see above).
      $nl           is the newline character.
+     $TEWIBA_COLORS    Colors for the tewiba messages, in the same syntax as
+                   LS_COLORS (see man dircolors), as colon-separated key=value
+                   pairs, where value is a set of color codes separated by 
+                   semicolons. You can set it at will, the default being:
+                   "none=0:error=31:fatal=1;31:info=36:title=34:ok=32:\
+                    allok=32;4:warning=35"
+                   and you can extend it with any keys for use in your own 
+                   TECHO statements.
+                   The keys being:
+                     none      no style
+                     error     error messages
+                     fatal     fatal or total error messages
+                     info      misc information (e.g. file skipped)
+                     title     the title of a section, e.g. a test file name
+                     ok        test result OK
+                     allok     final result: all tests OK
+                     warning   not a test failure, but something is fishy
      $TEWIBA       the version number of tewiba. Uses semantic versioning.
                    Trick: put after #!/bin/bash the line:
                    [ -n "$TEWIBA" ] || exec tewiba -v "$0"
@@ -93,8 +118,8 @@ Filenames beginning with a "." "#" "_" or ending with "~" are ignored
      tests, to clean the temporary data. tewiba traps the signal 0 for this,
      so you have nothing to do if you do not use "trap" in your tests.
      If you redefine trap 0 in your tests, or in a script you source, you 
-     should either make your trap function also call TCLEANUP, or redo a
-     "trap TCLEANUP 0" at the end of your tests.
+     should make your trap function also call TCLEANUP, and redo a
+     "trap TCLEANUP 0" when you do not use a trap 0 anymore.
 
 Options:
    -v      verbose: prints each test name as it is run, as well as its stdout
@@ -170,6 +195,9 @@ export tmp=/tmp/tewiba.$$
 export nl=$'\n' #'
 export TFAILS=0
 export TOTEST
+# normal error fatalerror info filename ok allok warning. See man dircolors
+export TEWIBA_COLORS; [ -z "$TEWIBA_COLORS" ] && \
+    TEWIBA_COLORS=':-none=0:error=31:fatal=1;31:info=36:title=34:ok=32:allok=32;4:warning=35'
 # Except the internal ones below, that start with an underscore "_"
 export _ts_failures=0		# cumulative total of TFAILS
 export _twtmp=/tmp/tewiba-main.$$ # tewiba-reserved temp zone
@@ -186,14 +214,12 @@ export _TEWIBA_IGNORE='^$'      # regexp for ignored files
 TLEVEL(){ [ -z "$TLEVELS" ] || [[ $* =~ [$TLEVELS] ]] || _ts_skip; }
 TLEVEL_ONLY(){ [[ $* =~ [$TLEVELS] ]] || _ts_skip; }
 TEST(){ _TEST_CURRENT="$*"; TECHO "== $*"; }
-TERR(){ echo "***TEST ERROR ${_TEST_CURRENT}*** $*" >&3; let TFAILS++;}
+TERR(){ TECHO -fc er  "***TEST ERROR ${_TEST_CURRENT}*** $*"; let TFAILS++;}
 FERR(){
-    echo "***FATAL ERROR ${_TEST_CURRENT}*** $*" >&3; let TFAILS++
+    TECHO -fc fa "***FATAL ERROR ${_TEST_CURRENT}*** $*"; let TFAILS++
     _ts_exit $TFAILS
 }
 TEND(){ _ts_exit $TFAILS; }
-TECHO(){ $TV && TECHOF "$@" || return;}
-TECHOF(){ echo "$@" >&3;}
 TINIT(){
     $ts_standalone && return
     local id; _TINITS=
@@ -205,12 +231,25 @@ TINIT(){
     done
     _tinits_push $_TINITS
 }
-TCLEANUP(){ # with guards to avoid disaster if something undefined the vars
-    ts_chdir
-    [ -n "$_twtmp" ] && rm -rf $_twtmp $_twtmp.*
-    [ -n "$tmp" ] && rm -rf $tmp $tmp.*
+
+# Printing tewiba messages out of the way of stdout & stderr of the tests
+TECHO(){
+    local opt normal=true key eopt cs ce 
+    OPTIND=1; while getopts 'vfnc:' opt; do case "$opt" in
+	v) :;;
+        f) normal=false;;
+        n) eopt='-n';;
+        c) key="${OPTARG//[^[:alpha:]]/}";;
+    esac; done; shift $((OPTIND-1))
+    $normal && ! $TV && return
+    if [ -n "$key" ] && [ -t 3 ] && \
+	[[ $TEWIBA_COLORS =~ (^|:)$key[[:alpha:]]*=([^:]*) ]]; then
+	cs=$'\e['${BASH_REMATCH[2]}m; ce=$'\e[0m'
+	echo $eopt "$cs""$@""$ce" >&3;
+    else
+	echo $eopt "$@" >&3;
+    fi
 }
-trap TCLEANUP 0
 
 # Usage: DOTEST [options] command-to-test its-options...
 DOTEST(){
@@ -253,6 +292,13 @@ TEWIBA_IGNORE(){
     _TEWIBA_IGNORE="${_TEWIBA_IGNORE/%|/)}"
 }
 
+TCLEANUP(){ # with guards to avoid disaster if something undefined the vars
+    ts_chdir
+    [ -n "$_twtmp" ] && rm -rf $_twtmp $_twtmp.*
+    [ -n "$tmp" ] && rm -rf $tmp $tmp.*
+}
+trap TCLEANUP 0
+
 # push back the TINITS from the child test process to the underlying tewiba
 _tinits_push(){ echo "$_cd $*" >>$_twtmp.endids;}
 
@@ -263,10 +309,10 @@ _ts_exit(){ exit "${1:-0}"; }
 _ts_skip(){ [ -n "$_TSKIP" ] && >$_TSKIP; exit 0; }
 
 # source if exist, and trace if verbose 
-_ts_source(){ [ -f "$1" ] && { TECHO "== Sourcing $1"; . "$1";};}
+_ts_source(){ [ -f "$1" ] && { TECHO -c ti "== Sourcing $1"; . "$1";};}
 
 # export these functions to be usable in test scripts
-export -f TLEVEL_ONLY TLEVEL TEST TERR FERR TEND TECHO TECHOF TINIT TCLEANUP \
+export -f TLEVEL_ONLY TLEVEL TEST TERR FERR TEND TECHO TINIT TCLEANUP \
  DOTEST TEWIBA_IGNORE \
     _tinits_push _ts_exit _ts_skip _ts_source
 
@@ -393,29 +439,29 @@ ts_test(){
         # RUN TEST in Trace Mode
 	bash -x "$t" >>$_debuglog 2>&1 3>&1; status=$? # merge all outputs
     else
-	TECHO "== Test file: $f:"
+	TECHO -c ti "== Test file: $f:"
 	_TSKIP=$_twtmp.skip.$$
         # RUN TEST
 	"$t" 2>$_twtmp.err >$_twtmp.out; status=$?
 	if $TV && test -s $_twtmp.out; then print_indent $_twtmp.out; fi
 	if [ -e "$_TSKIP" ]; then
-	    TECHO "   Skipped"
+	    TECHO -c in "   Skipped"
 	    rm -f "$_TSKIP"
 	else
 	    let '_ts_failures += status'
 	    if [ $status == 0 ]; then
 		if test -s $_twtmp.err; then 
-		    if $TV; then TECHO "== OK, but printed on stderr:"
-		    else TECHOF "###Warning: test $f OK, but printed on stderr:"
+		    if $TV; then TECHO -c wa "== OK, but printed on stderr:"
+		    else TECHO -fc wa "###Warning: test $f OK, but printed on stderr:"
 		    fi
 		    print_indent $_twtmp.err
 		else
-		    TECHO "== OK"
+		    TECHO -c ok "== OK"
 		fi
 	    else
-		if $TV; then TECHO "***ERRORS:$status"
+		if $TV; then TECHO -c er "***ERRORS:$status"
 		else 
-		    TECHOF "***FAILED ($status ERRORS): $f"
+		    TECHO -fc er "***FAILED ($status ERRORS): $f"
 		    if test -s $_twtmp.err; then print_indent $_twtmp.err; fi
 		fi
 	    fi
@@ -457,9 +503,9 @@ fi
 [ -n "$_cd" ] && { ts_chdir; _cd=;}
 
 ############################################ Epilogue: print results, and exit
-if [ $_ts_failures = 0 ]; then V "All tests OK =="
-else echo "== ***** Total tests failed: $_ts_failures *****"
+if [ $_ts_failures = 0 ]; then TECHO -c ao "All tests OK =="
+else TECHO -fc fa "== ***** Total tests failed: $_ts_failures *****"
 fi
-$_debug  && TECHOF "== log of execution in $_debuglog for $*"
+$_debug  && TECHO -fc no "== log of execution in $_debuglog for $*"
 [ -n "$statusfile" ] && echo "$_ts_failures" >"$statusfile"
 _ts_exit $_ts_failures
